language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'>=5.5.1'
- tools/install_modules.py $TRAVIS_BRANCH
script:
- git reset --hard
- npm run test
- npm run build
deploy:
- provider: releases
  api_key:
    secure: AKZefc+oQWOuXAK7ytS2tFgEmenpGP8gHijYA8BZNqA4HhwWWYYFWAHaGVrVGgEcnHAJBAqee/smw2przpka12IqccyfhvSng0uhPU7HvWdqO/VDW38d+JmneExiCvn1Nw7N+xwoX65FRn/jDlsooUeAqk0rn5Gj6CBbzk6yf7o=
  skip_cleanup: true
  file_glob: true
  file: build/production/Neon*.zip
  on:
    repo: NeApp/neon-extension-firefox
    tags: true
- provider: bintray
  key:
    secure: VPZRZxfyFKRPTN70BSmud8du98gLe2k17yaMmHu31MbEsjbfVWLELmjL2367hLhNmUpgS5nP12kQAYLAaWkR65rUrDlxPTaHIO6wYTfXfC3auSSnGc0wBOmEBhRg/xIkXhbkLszbCADpsAnVHPdzPhSLC0MkLI4dNZKPJnqHqW8=
  file: build/production/bintray.json
  user: neapp-ci
  on:
    repo: NeApp/neon-extension-firefox
    all_branches: true
